[project]
name = "agents-workshop"
version = "0.1.0"
description = "This project is a set of lessons that explore building AI Agents."
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "pydantic",
    "openai",
    "requests",
    "backoff",
    "halo",
]
